# Environment variables for Supabase configuration
version: '3.9'

services:
  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    
    ports:
      - "3000:80"
    restart: unless-stopped
